### ISSUE TITLE
No module named 'pysms' 

### ISSUE THREAD

**Issue by lichengzhang1** [markirch/sat-modulo-symmetries#24]
Previously, everything was running smoothly. However, today, when I used the program, it indicated that I don't have the psyms module.  Very strange.

```
 python ./pysms/graph_builder.py -v 11 --num-edges-low 20 --Ck-free 5 --args-SMS " --planar 5 "
Traceback (most recent call last):
  File "/mnt/e/zlc_phd_work/graphtools/sat-modulo-symmetries/./pysms/graph_builder.py", line 7, in <module>
    from pysms.counters import *
ModuleNotFoundError: No module named 'pysms' 
```

I have already activated the Python virtual environment created earlier (`source ./myenv/bin/activate`) . How can I address this without reinstalling the entire software? My system is Arch Linux.

**Comment by lichengzhang1** [comment]
Sorry. I rebuilt and discovered that the possible cause of the error was that I changed the name of the parent directory.

**Comment by peitl** [comment]
@lichengzhang1 also note that once you installed SMS, you should be ablto to run `python -m pysms.graph_builder ...` instead of `python ./pysms/graph_builder.py`, where the former will work in any working directory (I'm not sure whether this was related to your issue).

Regarding GCC 13, I'm glad to hear you made it work, I haven't got a system with GCC 13 at the moment, but I'll try to see if I can fix the includes so that it works on GCC 13 as well.
